openapi: 3.0.0
info:
  title: Hello world
  version: 1.0.0
servers:
- url: http://localhost:3000/api
tags: []
paths:
  /:
    get:
      responses:
        '200':
          description: ''
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /hej:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Hejsan'
  /hej2:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Hejsan'
        '500':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CoolErrorType'
components:
  schemas:
    CoolErrorType:
      type: object
      title: CoolErrorType
      required:
      - a
      - b
      - c
      properties:
        a:
          type: integer
          format: uint32
        b:
          type: integer
          format: int32
        c:
          type: string
    Hejsan:
      type: object
      title: Hejsan
      required:
      - hej
      properties:
        hej:
          type: integer
          format: uint64
