/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Hello world
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  Hejsan
} from '../model';


export const getGetResponseMock = (): string => (faker.word.sample())

export const getGetHejResponseMock = (overrideResponse: Partial<Extract<Hejsan, object>> = {}): Hejsan => ({hej: faker.number.int(), ...overrideResponse})

