/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Hello world
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Hejsan
} from '../model';


export const getGetResponseMock = (): string => (faker.word.sample())

export const getGetHejResponseMock = (overrideResponse: Partial<Extract<Hejsan, object>> = {}): Hejsan => ({hej: faker.number.int(), ...overrideResponse})


export const getGetMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.get('*/', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {

  const resolvedBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetResponseMock();
    const textBody = typeof resolvedBody === 'string' ? resolvedBody : JSON.stringify(resolvedBody ?? null);
    return HttpResponse.text(textBody,
      { status: 200
      })
  }, options)
}

export const getGetHejMockHandler = (overrideResponse?: Hejsan | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Hejsan> | Hejsan), options?: RequestHandlerOptions) => {
  return http.get('*/hej', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetHejResponseMock(),
      { status: 200
      })
  }, options)
}
export const getDefaultMock = () => [
  getGetMockHandler(),
  getGetHejMockHandler()
]
